### ISSUE TITLE
This is really good project but only for Indonesia sadly

### ISSUE THREAD

**Issue by ouam3r** [van-geaux/indonesia_gmaps_scraper#2]
I have played with your script for a couple minutes and enjoyed it. Can you adjust it to work for other continent like Europe or Africa?

**Comment by van-geaux** [comment]
I will see what I can do about that

**Comment by ouam3r** [comment]
I am still interested if you are. Let's do a custom work then, what do you think?

**Comment by van-geaux** [comment]
I have updated the code quite a bit since last week to better fit global usage, mainly:
1. changing the language of the options and logs
2. changing the scraping result and search table database scheme
3. added failovers for failed detailed scraping

All that's left is changing the scheme of the search database and how it got filled, also some optimizations
For now it works by inserting indonesia's postal codes from indonesia postal website in main.db (table randomized_pos)

And to use it for other countries, let's say england for example, user still need to manually create that table
I have the basic idea to automate that and he sample code ready but it still not there yet

The todo lists are mainly:
1. make sure the scrolling works for whatever language environment being used, for now it's indonesian and english because it search for something "You've reached the end of the list." in the html to determine if it finished scrolling and it can change depending on user's language environment
2. change the entirety of search database scheme
3. create a way for user to easily populate the search database

So yeah, for now it works but user just need to manually populate randomized_pos table in main.db
Oh also it's definitely a breaking change so you need to reclone the whole thing

**Comment by ouam3r** [comment]
![image](https://github.com/user-attachments/assets/82570c2c-bf0a-4d6d-9fcc-56370beb37dd)

Am I missing something?

**Comment by van-geaux** [comment]
Yes, you missed the database
I fixed it so it works with templates (Indonesian) if you don't have one already

Also it works with global addresses now, you just need to fill the area/region data according to the template you want and point to the file accordingly in the configuration

Alas the limitation is in scrolling:
The scroll can only detect "You've reached the end of the list." or "Anda telah mencapai akhir daftar." so for global usage, the chrome/computer needs to be in english
Just to make sure, maybe also use only english-speaking countries if using proxy
